import sys
import os

from Features.Generate import *
from pandas.core.frame import DataFrame
from step3_getScore import *

sys.path.append('..')
print(os.getcwd())

input_seq = "CAGGATTTGTTTTATCCAACTCATCCCTTGACATCGTGCTTCACGATACATACTATGTAGTAGCCCATTTCCACTATGTTCTATCAATGGGAGCAGTGTTTGCTATCATAGCAGGATTTGTTCACTGATTCCCATTATTTTCAGGCTTCACCCTAGATGACACATGAGCAAAAGCCCACTTCGCCATCATATTCGTAGGAGTAAACATAACATTCTTCCCTCAACATTTCCTGGGCCTTTCAGGAATACCACGACGCTACTCAGACTACCCAGATGCTTACACCACATGAAACACTGTCTCTTCTATAGGATCATTTATTTCACTAACAGCTGTTCTCATCATGATCTTTATAATTTGAGAGGCCTTTGCTTCAAAACGAGAAGTAATATCAGTATCGTATGCTTCAACAAATTTAGAATGACTTCATGGCTGCCCTCCACCATATCACACATTCGAGGAACCAACCTATGTAAAAGTAAAATAAGAAAGGAAGGAATCGAACCCCCTAAAATTGGTTTCAAGCCAATCTCATATCCTATATGTCTTTCTCAATAAGATATTAGTAAAATCAATTACATAACTTTGTCAAAGTTAAATTATAGATCAATAATCTATATATCTTATATGGCCTACCCATTCCAACTTGGTCTACAAGACGCCACATCCCCTATTATAGAAGAGCTAATAAATTTCCATGATCACACACTAATAATTGTTTTCCTAATTAGCTCCTTAGTCCTCTATATCATCTCGCTAATATTAACAACAAAACTAACACATACAAGCACAATAGATGCACAAGAAGTTGAAACCATTTGAACTATTCTACCAGCTGTAATCCTTATCATAATTGCTCTCCCCTCTCTACGCATTCTATATATAATAGACGAAATCAACAACCCCGTATTAACCGTTAAAACCATAGGGCACCAATGATACTGAAGCTACGAATATACTGACTATGAAGACCTATGCTTTGATTCATATATAATCCCAACAAACGACCTAAAACCTGGTGAACTACGACTGCTAGAAGTTGATAACCGAGTCGTTCTGCCAATAGAACTTCCAATCCGTATATTAATTTCATCTGAAGACGTCCTCCACTCATGAGCAGTCCCCTCCCTAGGACTTAAAACTGATGCCATCCCAGGCCGACTAAATCAAGCAACAGTAACATCAAACCGACCAGGGTTATTCTATGGCCAATGCTCTGAAATTTGTGGATCTAACCATAGCTTTATGCCCATTGTCCTAGAAATGGTTCCACTAAAATATTTCGAAAACTGATCTGCTTCAATAATTTAATTTCACAAAAAAAAAAAAAAAAAAC"
input_feature = generateNumericSample(seq=input_seq)
print(input_feature)

a=[input_feature]#包含两个不同的子列表[1,2,3,4]和[5,6,7,8]
data=DataFrame(a)#这时候是以行为标准写入的
data.columns = ['ORF.Max.Len', 'ORF.Max.Cov', 'hexamer_orf_step1', 'hexamer_orf_step3', 'hexamer_Full_length_step1',
             'hexamer_Full_length_step3', 'FickettScore_orf', 'FickettScore_fulllength', 'freq_A', 'freq_T', 'freq_G',
             'freq_C', 'AT_trans', 'AG_trans', 'AC_trans', 'TG_trans', 'TC_trans', 'GC_trans', 'A0_dis', 'A1_dis',
             'A2_dis', 'A3_dis', 'A4_dis', 'T0_dis', 'T1_dis', 'T2_dis', 'T3_dis', 'T4_dis', 'G0_dis', 'G1_dis',
             'G2_dis', 'G3_dis', 'G4_dis', 'C0_dis', 'C1_dis', 'C2_dis', 'C3_dis', 'C4_dis', 'pI_orf', 'pI_full_length',
             'Signal.Peak', 'Average.Power', 'SNR', '0%', '25%', '50%', '75%', '100%', 'MFE']
print(data)

score = getAttention_Score(all_data=data, ndim=49)

print(score)